models:
  - name: bronze_bookings
    # schema: bronze
    config:
      materialized: table
  - name: bronze_hosts
    # schema: bronze
    config:
      materialized: table
  - name: bronze_listings
    # schema: bronze
    config:
      materialized: table